id: A2C42960B
title: Concise Daily Practice of Vajrasattva
type: translation
pechas:
- IC1FF5276
- I247648F2
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:33:46.543225
  last_modified_at: 2023-01-04 11:33:46.543240
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  IC1FF5276/1163: 0A70
  I247648F2/6438: 0A70
